groups:
  - name: test-alert-group
    rules:
      - alert: TestSlackAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: test
        annotations:
          summary: "🚨 Test Alert to Slack"
          description: "This is a *test alert* from vmalert to Alertmanager to Slack. If you're seeing this, integration is working! 🎉"

