{
 "title": "vm",
 "description": "OpenTelemetry Collector otelcol-contrib hostmetrics (Node Exporter)",
 "tags": [
  "linux",
  "otelcol-contrib",
  "opentelemetry"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(system_cpu_time{host_name=\"$host\"},host_name)"
    }
   },
   { "name": "port" }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "CPU utilization percentage is being calculated on a per-host basis within a specific service namespace.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state!=\"idle\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total\n{host_name=~\"${host}.*\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_average_5m{host_name=~\"${host}.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_average_15m{host_name=~\"${host}.*\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{ host_name=~\"${host}.*\", state=\"free\" }"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_usage_bytes{ host_name=~\"${host}.*\", state=\"used\" }"
    }
   ]
  },
  {
   "title": "FS Used",
   "type": "gauge",
   "description": "Used FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_filesystem_utilization_ratio{host_name=~\"${host}.*\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_logical_count{ host_name=~\"${host}.*\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{host_name=~\"${host}.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS Total",
   "type": "stat",
   "description": "Total FS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(system_filesystem_usage_bytes{host_name=~\"${host}.*\", state=\"free\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{host_name=~\"${host}.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_paging_usage_bytes{host_name=~\"${host}.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state=\"system\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state=\"user\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state=\"wait\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Busy Wait"
    },
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state=~\".*irq\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state!~\".*irq\", state!=\"idle\", state!=\"user\", state!=\"wait\", state!=\"system\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(host_name) (irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\", state=\"idle\"}[$__rate_interval])) / on(host_name) group_left sum by (host_name)((irate(system_cpu_time_seconds_total{host_name=~\"${host}.*\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{host_name=~\"${host}.*\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "system_memory_usage_bytes{host_name=~\"${host}.*\", state=\"free\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(system_memory_usage_bytes{host_name=~\"${host}.*\", state=~\"cached|buffered\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(system_paging_usage_bytes{host_name=~\"${host}.*\", state=\"used\"})",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{host_name=~\"${host}.*\", direction=\"receive\"}[$__interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(system_network_io_bytes_total{host_name=~\"${host}.*\", direction=\"transmit\"}[$__interval])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations_total{host_name=~\"${host}.*\", direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(system_disk_operations_total{host_name=~\"${host}.*\", direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(system_disk_io_bytes_total{host_name=~\"${host}.*\", direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(system_disk_io_bytes_total{host_name=~\"${host}.*\", direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_filesystem_utilization_ratio{host_name=~\"${host}.*\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU utilization ratio per process",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization_ratio{ host_name=~\"${host}.*\"}",
     "legendFormat": "{{process_command}} / {{state}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "description": "This metric shows how much memory (RAM) a specific process is using.\n",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{host_name=~\"${host}.*\"}",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "This metric shows how many bytes a specific process is reading/writing to the disk.\n\nIt is useful for tracking total disk I/O usage.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(process_disk_io_bytes_total{ host_name=~\"${host}.*\" }[$__interval])",
     "legendFormat": "{{process_command}} / {{direction}}"
    }
   ]
  }
 ]
}