global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.219:9090']  

rule_files:
  - "/home/opstree/prometheus-config/alert_rules.yml"  

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'   
