global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus server itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # OpenTelemetry Collector metrics endpoint
  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:9464']

  # VictoriaMetrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  # Loki for logs
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  
  # - "alert.rules"
